# Generated by Django 5.2.3 on 2025-07-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("mid", models.AutoField(primary_key=True, serialize=False)),
                ("mname", models.CharField(max_length=50)),
                ("mdir", models.CharField(max_length=50)),
                ("mcont", models.CharField(max_length=500)),
                ("myear", models.IntegerField()),
                ("mlang", models.CharField(max_length=50)),
                ("mtype", models.JSONField(default=list)),
            ],
        ),
    ]
