# Generated by Django 5.2.3 on 2025-07-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="mimg",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="movie",
            name="mvideo",
            field=models.FileField(null=True, upload_to="videos/"),
        ),
    ]
