# Generated by Django 5.2.3 on 2025-07-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_movie_mimg_movie_mvideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="mlang",
            field=models.JSONField(default=list),
        ),
    ]
